# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jasper/Documents/omnidir_stereo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jasper/Documents/omnidir_stereo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasper/Documents/omnidir_stereo/CMakeFiles /home/jasper/Documents/omnidir_stereo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jasper/Documents/omnidir_stereo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named omnidir_stereo

# Build rule for target.
omnidir_stereo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 omnidir_stereo
.PHONY : omnidir_stereo

# fast build rule for target.
omnidir_stereo/fast:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/build
.PHONY : omnidir_stereo/fast

src/SGMStereo.o: src/SGMStereo.cpp.o

.PHONY : src/SGMStereo.o

# target to build an object file
src/SGMStereo.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/SGMStereo.cpp.o
.PHONY : src/SGMStereo.cpp.o

src/SGMStereo.i: src/SGMStereo.cpp.i

.PHONY : src/SGMStereo.i

# target to preprocess a source file
src/SGMStereo.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/SGMStereo.cpp.i
.PHONY : src/SGMStereo.cpp.i

src/SGMStereo.s: src/SGMStereo.cpp.s

.PHONY : src/SGMStereo.s

# target to generate assembly for a file
src/SGMStereo.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/SGMStereo.cpp.s
.PHONY : src/SGMStereo.cpp.s

src/SPSStereo.o: src/SPSStereo.cpp.o

.PHONY : src/SPSStereo.o

# target to build an object file
src/SPSStereo.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/SPSStereo.cpp.o
.PHONY : src/SPSStereo.cpp.o

src/SPSStereo.i: src/SPSStereo.cpp.i

.PHONY : src/SPSStereo.i

# target to preprocess a source file
src/SPSStereo.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/SPSStereo.cpp.i
.PHONY : src/SPSStereo.cpp.i

src/SPSStereo.s: src/SPSStereo.cpp.s

.PHONY : src/SPSStereo.s

# target to generate assembly for a file
src/SPSStereo.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/SPSStereo.cpp.s
.PHONY : src/SPSStereo.cpp.s

src/calcChessboardCorners.o: src/calcChessboardCorners.cpp.o

.PHONY : src/calcChessboardCorners.o

# target to build an object file
src/calcChessboardCorners.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/calcChessboardCorners.cpp.o
.PHONY : src/calcChessboardCorners.cpp.o

src/calcChessboardCorners.i: src/calcChessboardCorners.cpp.i

.PHONY : src/calcChessboardCorners.i

# target to preprocess a source file
src/calcChessboardCorners.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/calcChessboardCorners.cpp.i
.PHONY : src/calcChessboardCorners.cpp.i

src/calcChessboardCorners.s: src/calcChessboardCorners.cpp.s

.PHONY : src/calcChessboardCorners.s

# target to generate assembly for a file
src/calcChessboardCorners.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/calcChessboardCorners.cpp.s
.PHONY : src/calcChessboardCorners.cpp.s

src/calib_img_gen.o: src/calib_img_gen.cpp.o

.PHONY : src/calib_img_gen.o

# target to build an object file
src/calib_img_gen.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/calib_img_gen.cpp.o
.PHONY : src/calib_img_gen.cpp.o

src/calib_img_gen.i: src/calib_img_gen.cpp.i

.PHONY : src/calib_img_gen.i

# target to preprocess a source file
src/calib_img_gen.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/calib_img_gen.cpp.i
.PHONY : src/calib_img_gen.cpp.i

src/calib_img_gen.s: src/calib_img_gen.cpp.s

.PHONY : src/calib_img_gen.s

# target to generate assembly for a file
src/calib_img_gen.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/calib_img_gen.cpp.s
.PHONY : src/calib_img_gen.cpp.s

src/detectChessboardCorners.o: src/detectChessboardCorners.cpp.o

.PHONY : src/detectChessboardCorners.o

# target to build an object file
src/detectChessboardCorners.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/detectChessboardCorners.cpp.o
.PHONY : src/detectChessboardCorners.cpp.o

src/detectChessboardCorners.i: src/detectChessboardCorners.cpp.i

.PHONY : src/detectChessboardCorners.i

# target to preprocess a source file
src/detectChessboardCorners.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/detectChessboardCorners.cpp.i
.PHONY : src/detectChessboardCorners.cpp.i

src/detectChessboardCorners.s: src/detectChessboardCorners.cpp.s

.PHONY : src/detectChessboardCorners.s

# target to generate assembly for a file
src/detectChessboardCorners.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/detectChessboardCorners.cpp.s
.PHONY : src/detectChessboardCorners.cpp.s

src/globVector.o: src/globVector.cpp.o

.PHONY : src/globVector.o

# target to build an object file
src/globVector.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/globVector.cpp.o
.PHONY : src/globVector.cpp.o

src/globVector.i: src/globVector.cpp.i

.PHONY : src/globVector.i

# target to preprocess a source file
src/globVector.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/globVector.cpp.i
.PHONY : src/globVector.cpp.i

src/globVector.s: src/globVector.cpp.s

.PHONY : src/globVector.s

# target to generate assembly for a file
src/globVector.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/globVector.cpp.s
.PHONY : src/globVector.cpp.s

src/loadCalibration.o: src/loadCalibration.cpp.o

.PHONY : src/loadCalibration.o

# target to build an object file
src/loadCalibration.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/loadCalibration.cpp.o
.PHONY : src/loadCalibration.cpp.o

src/loadCalibration.i: src/loadCalibration.cpp.i

.PHONY : src/loadCalibration.i

# target to preprocess a source file
src/loadCalibration.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/loadCalibration.cpp.i
.PHONY : src/loadCalibration.cpp.i

src/loadCalibration.s: src/loadCalibration.cpp.s

.PHONY : src/loadCalibration.s

# target to generate assembly for a file
src/loadCalibration.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/loadCalibration.cpp.s
.PHONY : src/loadCalibration.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pointCloud.o: src/pointCloud.cpp.o

.PHONY : src/pointCloud.o

# target to build an object file
src/pointCloud.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/pointCloud.cpp.o
.PHONY : src/pointCloud.cpp.o

src/pointCloud.i: src/pointCloud.cpp.i

.PHONY : src/pointCloud.i

# target to preprocess a source file
src/pointCloud.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/pointCloud.cpp.i
.PHONY : src/pointCloud.cpp.i

src/pointCloud.s: src/pointCloud.cpp.s

.PHONY : src/pointCloud.s

# target to generate assembly for a file
src/pointCloud.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/pointCloud.cpp.s
.PHONY : src/pointCloud.cpp.s

src/reprojectionError.o: src/reprojectionError.cpp.o

.PHONY : src/reprojectionError.o

# target to build an object file
src/reprojectionError.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/reprojectionError.cpp.o
.PHONY : src/reprojectionError.cpp.o

src/reprojectionError.i: src/reprojectionError.cpp.i

.PHONY : src/reprojectionError.i

# target to preprocess a source file
src/reprojectionError.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/reprojectionError.cpp.i
.PHONY : src/reprojectionError.cpp.i

src/reprojectionError.s: src/reprojectionError.cpp.s

.PHONY : src/reprojectionError.s

# target to generate assembly for a file
src/reprojectionError.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/reprojectionError.cpp.s
.PHONY : src/reprojectionError.cpp.s

src/saveCalibration.o: src/saveCalibration.cpp.o

.PHONY : src/saveCalibration.o

# target to build an object file
src/saveCalibration.cpp.o:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/saveCalibration.cpp.o
.PHONY : src/saveCalibration.cpp.o

src/saveCalibration.i: src/saveCalibration.cpp.i

.PHONY : src/saveCalibration.i

# target to preprocess a source file
src/saveCalibration.cpp.i:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/saveCalibration.cpp.i
.PHONY : src/saveCalibration.cpp.i

src/saveCalibration.s: src/saveCalibration.cpp.s

.PHONY : src/saveCalibration.s

# target to generate assembly for a file
src/saveCalibration.cpp.s:
	$(MAKE) -f CMakeFiles/omnidir_stereo.dir/build.make CMakeFiles/omnidir_stereo.dir/src/saveCalibration.cpp.s
.PHONY : src/saveCalibration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... omnidir_stereo"
	@echo "... edit_cache"
	@echo "... src/SGMStereo.o"
	@echo "... src/SGMStereo.i"
	@echo "... src/SGMStereo.s"
	@echo "... src/SPSStereo.o"
	@echo "... src/SPSStereo.i"
	@echo "... src/SPSStereo.s"
	@echo "... src/calcChessboardCorners.o"
	@echo "... src/calcChessboardCorners.i"
	@echo "... src/calcChessboardCorners.s"
	@echo "... src/calib_img_gen.o"
	@echo "... src/calib_img_gen.i"
	@echo "... src/calib_img_gen.s"
	@echo "... src/detectChessboardCorners.o"
	@echo "... src/detectChessboardCorners.i"
	@echo "... src/detectChessboardCorners.s"
	@echo "... src/globVector.o"
	@echo "... src/globVector.i"
	@echo "... src/globVector.s"
	@echo "... src/loadCalibration.o"
	@echo "... src/loadCalibration.i"
	@echo "... src/loadCalibration.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pointCloud.o"
	@echo "... src/pointCloud.i"
	@echo "... src/pointCloud.s"
	@echo "... src/reprojectionError.o"
	@echo "... src/reprojectionError.i"
	@echo "... src/reprojectionError.s"
	@echo "... src/saveCalibration.o"
	@echo "... src/saveCalibration.i"
	@echo "... src/saveCalibration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

